export interface ApiEndpoint {
  name: string
  description: string
  method: 'GET' | 'POST'
  endpoint: string
  category: string
  tags: string[]
  cost: number
  params: { name: string; type: string; required: boolean; description: string }[]
  body?: { name: string; type: string; required: boolean; description: string }[]
  example: { request: string; response: string }
}

export const endpoints: ApiEndpoint[] = [
  { name: 'Send Message', description: 'Send message via WhatsApp, Telegram, or Discord', method: 'POST', endpoint: '/api/send', category: 'SEND', tags: ['send', 'message', 'wa', 'tg'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }], body: [{ name: 'platform', type: 'string', required: true, description: 'whatsapp | telegram | discord' }, { name: 'message', type: 'string', required: true, description: 'Message content' }, { name: 'phoneNumber', type: 'string', required: false, description: 'Phone (WhatsApp)' }, { name: 'chatId', type: 'string', required: false, description: 'Chat ID (Telegram)' }, { name: 'channelId', type: 'string', required: false, description: 'Channel ID (Discord)' }], example: { request: 'POST /api/send\n{"platform":"whatsapp","phoneNumber":"62812","message":"Hello"}', response: '{"status":true,"data":{"platform":"whatsapp","costCredits":1}}' } },

  { name: 'Text to MP3', description: 'Convert text to downloadable MP3 audio', method: 'GET', endpoint: '/api/tools/text-to-mp3', category: 'TEXT', tags: ['tts', 'mp3', 'audio'], cost: 2, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'text', type: 'query', required: true, description: 'Text to convert (max 5000)' }, { name: 'lang', type: 'query', required: false, description: 'Language code (default: id)' }], example: { request: 'GET /api/tools/text-to-mp3?text=Halo', response: '{"status":true,"data":{"downloadUrl":"https://..."}}' } },
  { name: 'Word Count', description: 'Count words, characters, sentences', method: 'GET', endpoint: '/api/tools/word-count', category: 'TEXT', tags: ['word', 'count'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'text', type: 'query', required: true, description: 'Text to analyze' }], example: { request: 'GET /api/tools/word-count?text=Hello+World', response: '{"status":true,"data":{"words":2,"characters":11}}' } },
  { name: 'Base64', description: 'Encode or decode Base64 text', method: 'GET', endpoint: '/api/tools/base64', category: 'TEXT', tags: ['base64', 'encode', 'decode'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'text', type: 'query', required: true, description: 'Text to encode/decode' }, { name: 'mode', type: 'query', required: false, description: 'encode | decode (default: encode)' }], example: { request: 'GET /api/tools/base64?text=Hello', response: '{"status":true,"data":{"output":"SGVsbG8="}}' } },
  { name: 'Slugify', description: 'Convert text to URL-friendly slug', method: 'GET', endpoint: '/api/tools/slugify', category: 'TEXT', tags: ['slug', 'url'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'text', type: 'query', required: true, description: 'Text to slugify' }], example: { request: 'GET /api/tools/slugify?text=Hello+World', response: '{"status":true,"data":{"slug":"hello-world"}}' } },
  { name: 'Reverse Text', description: 'Reverse text or words', method: 'GET', endpoint: '/api/tools/reverse-text', category: 'TEXT', tags: ['reverse', 'text'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'text', type: 'query', required: true, description: 'Text to reverse' }], example: { request: 'GET /api/tools/reverse-text?text=Hello', response: '{"status":true,"data":{"reversed":"olleH"}}' } },
  { name: 'Lorem Ipsum', description: 'Generate placeholder text', method: 'GET', endpoint: '/api/tools/lorem-ipsum', category: 'TEXT', tags: ['lorem', 'placeholder'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'paragraphs', type: 'query', required: false, description: 'Number (default 3, max 20)' }], example: { request: 'GET /api/tools/lorem-ipsum?paragraphs=2', response: '{"status":true,"data":{"text":"Lorem ipsum..."}}' } },
  { name: 'Hash Generator', description: 'Generate MD5/SHA1/SHA256/SHA512 hash', method: 'GET', endpoint: '/api/tools/hash', category: 'TEXT', tags: ['hash', 'md5', 'sha256'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'text', type: 'query', required: true, description: 'Text to hash' }, { name: 'algo', type: 'query', required: false, description: 'md5 | sha1 | sha256 | sha512' }], example: { request: 'GET /api/tools/hash?text=Hello&algo=sha256', response: '{"status":true,"data":{"hash":"185f8db32..."}}' } },
  { name: 'Password Generator', description: 'Generate secure random passwords', method: 'GET', endpoint: '/api/tools/password-gen', category: 'TEXT', tags: ['password', 'random'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'length', type: 'query', required: false, description: 'Length 4-128 (default: 16)' }, { name: 'count', type: 'query', required: false, description: 'Count max 10' }], example: { request: 'GET /api/tools/password-gen?length=20', response: '{"status":true,"data":{"passwords":["abc123..."]}}' } },

  { name: 'Placeholder Image', description: 'Generate placeholder images', method: 'GET', endpoint: '/api/tools/placeholder', category: 'IMAGE', tags: ['placeholder', 'image'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'width', type: 'query', required: false, description: 'Width (default: 300)' }, { name: 'height', type: 'query', required: false, description: 'Height (default: 200)' }, { name: 'text', type: 'query', required: false, description: 'Text on image' }], example: { request: 'GET /api/tools/placeholder?width=400&height=300', response: '{"status":true,"data":{"url":"https://placehold.co/..."}}' } },
  { name: 'Avatar Generator', description: 'Generate avatar from initials', method: 'GET', endpoint: '/api/tools/avatar', category: 'IMAGE', tags: ['avatar', 'profile'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'name', type: 'query', required: false, description: 'Name for initials' }, { name: 'size', type: 'query', required: false, description: 'Size (default: 128)' }], example: { request: 'GET /api/tools/avatar?name=John+Doe', response: '{"status":true,"data":{"url":"https://ui-avatars.com/api/..."}}' } },
  { name: 'Color Info', description: 'Get color details from hex code', method: 'GET', endpoint: '/api/tools/color', category: 'IMAGE', tags: ['color', 'hex', 'rgb'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'hex', type: 'query', required: false, description: 'Hex color (default: #3b82f6)' }], example: { request: 'GET /api/tools/color?hex=#ff0000', response: '{"status":true,"data":{"hex":"#ff0000","rgb":{"r":255,"g":0,"b":0}}}' } },

  { name: 'YouTube Downloader', description: 'Download YouTube video as MP3/MP4', method: 'GET', endpoint: '/api/tools/ytdl', category: 'DOWNLOADER', tags: ['youtube', 'ytdl', 'mp3', 'mp4'], cost: 3, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'url', type: 'query', required: true, description: 'YouTube URL' }, { name: 'format', type: 'query', required: false, description: 'mp3 | mp4 (default: mp4)' }, { name: 'quality', type: 'query', required: false, description: '360/480/720/1080' }], example: { request: 'GET /api/tools/ytdl?url=https://youtu.be/xxx&format=mp3', response: '{"status":true,"data":{"downloadUrl":"https://...mp3"}}' } },
  { name: 'Instagram Downloader', description: 'Download Instagram posts/reels', method: 'GET', endpoint: '/api/tools/igdl', category: 'DOWNLOADER', tags: ['instagram', 'ig', 'download'], cost: 3, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'url', type: 'query', required: true, description: 'Instagram post/reel URL' }], example: { request: 'GET /api/tools/igdl?url=https://instagram.com/p/xxx', response: '{"status":true,"data":{"downloadUrl":"https://..."}}' } },
  { name: 'TikTok Downloader', description: 'Download TikTok video without watermark', method: 'GET', endpoint: '/api/tools/ttdl', category: 'DOWNLOADER', tags: ['tiktok', 'tt', 'download'], cost: 3, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'url', type: 'query', required: true, description: 'TikTok video URL' }], example: { request: 'GET /api/tools/ttdl?url=https://tiktok.com/@user/video/xxx', response: '{"status":true,"data":{"downloadUrl":"https://..."}}' } },
  { name: 'Twitter/X Downloader', description: 'Download Twitter/X videos and images', method: 'GET', endpoint: '/api/tools/xdl', category: 'DOWNLOADER', tags: ['twitter', 'x', 'tweet'], cost: 3, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'url', type: 'query', required: true, description: 'Twitter/X tweet URL' }], example: { request: 'GET /api/tools/xdl?url=https://twitter.com/user/status/xxx', response: '{"status":true,"data":{"downloadUrl":"https://..."}}' } },
  { name: 'Facebook Downloader', description: 'Download Facebook videos', method: 'GET', endpoint: '/api/tools/fbdl', category: 'DOWNLOADER', tags: ['facebook', 'fb', 'download'], cost: 3, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'url', type: 'query', required: true, description: 'Facebook video URL' }], example: { request: 'GET /api/tools/fbdl?url=https://facebook.com/watch?v=xxx', response: '{"status":true,"data":{"downloadUrl":"https://..."}}' } },

  { name: 'Anime Search', description: 'Search anime from MyAnimeList', method: 'GET', endpoint: '/api/tools/anime', category: 'ANIME', tags: ['anime', 'manga', 'mal'], cost: 2, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'q', type: 'query', required: true, description: 'Anime title' }], example: { request: 'GET /api/tools/anime?q=naruto', response: '{"status":true,"data":{"results":[{"title":"Naruto"}]}}' } },
  { name: 'Anime Detail', description: 'Get detailed anime info by MAL ID', method: 'GET', endpoint: '/api/tools/anime-detail', category: 'ANIME', tags: ['anime', 'detail'], cost: 2, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'id', type: 'query', required: true, description: 'MyAnimeList ID' }], example: { request: 'GET /api/tools/anime-detail?id=1', response: '{"status":true,"data":{"title":"Cowboy Bebop"}}' } },
  { name: 'Manga Search', description: 'Search manga from MyAnimeList', method: 'GET', endpoint: '/api/tools/manga', category: 'ANIME', tags: ['manga', 'comic'], cost: 2, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'q', type: 'query', required: true, description: 'Manga title' }], example: { request: 'GET /api/tools/manga?q=one+piece', response: '{"status":true,"data":{"results":[{"title":"One Piece"}]}}' } },
  { name: 'Character Search', description: 'Search anime characters', method: 'GET', endpoint: '/api/tools/character', category: 'ANIME', tags: ['character'], cost: 2, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'q', type: 'query', required: true, description: 'Character name' }], example: { request: 'GET /api/tools/character?q=naruto', response: '{"status":true,"data":{"results":[{"name":"Naruto"}]}}' } },
  { name: 'Anime Schedule', description: 'Get anime airing schedule', method: 'GET', endpoint: '/api/tools/anime-schedule', category: 'ANIME', tags: ['schedule', 'airing'], cost: 2, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'day', type: 'query', required: false, description: 'monday, tuesday, etc' }], example: { request: 'GET /api/tools/anime-schedule?day=monday', response: '{"status":true,"data":{"results":[...]}}' } },
  { name: 'Waifu Image', description: 'Get random anime/waifu images from waifu.im', method: 'GET', endpoint: '/api/tools/waifu-im', category: 'ANIME', tags: ['waifu', 'anime', 'neko'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'tags', type: 'query', required: false, description: 'waifu/neko/megumin/shinobu/etc' }, { name: 'limit', type: 'query', required: false, description: 'Number of images (1-10)' }], example: { request: 'GET /api/tools/waifu-im?tags=neko', response: '{"status":true,"data":{"count":1,"images":[{"url":"https://..."}]}}' } },

  { name: 'Lyrics', description: 'Search song lyrics', method: 'GET', endpoint: '/api/tools/lyrics', category: 'MEDIA', tags: ['lyrics', 'lirik', 'song'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'q', type: 'query', required: true, description: 'Song title' }], example: { request: 'GET /api/tools/lyrics?q=shape+of+you', response: '{"status":true,"data":{"title":"Shape of You","lyrics":"..."}}' } },
  { name: 'Spotify Info', description: 'Get Spotify track/album info', method: 'GET', endpoint: '/api/tools/spotify', category: 'MEDIA', tags: ['spotify', 'music'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'url', type: 'query', required: true, description: 'Spotify URL' }], example: { request: 'GET /api/tools/spotify?url=https://open.spotify.com/track/xxx', response: '{"status":true,"data":{"title":"Shape of You"}}' } },
  { name: 'Movie Search', description: 'Search movies and TV shows', method: 'GET', endpoint: '/api/tools/movie', category: 'MEDIA', tags: ['movie', 'film', 'imdb'], cost: 2, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'q', type: 'query', required: true, description: 'Movie title' }], example: { request: 'GET /api/tools/movie?q=inception', response: '{"status":true,"data":{"results":[{"title":"Inception"}]}}' } },
  { name: 'Book Search', description: 'Search books from Google Books', method: 'GET', endpoint: '/api/tools/book', category: 'MEDIA', tags: ['book', 'read'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'q', type: 'query', required: true, description: 'Book title or author' }], example: { request: 'GET /api/tools/book?q=atomic+habits', response: '{"status":true,"data":{"results":[{"title":"Atomic Habits"}]}}' } },

  { name: 'IP Lookup', description: 'Lookup geolocation for IP address', method: 'GET', endpoint: '/api/tools/ip-lookup', category: 'INFO', tags: ['ip', 'location', 'geo'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'ip', type: 'query', required: false, description: 'IP (empty = your IP)' }], example: { request: 'GET /api/tools/ip-lookup?ip=8.8.8.8', response: '{"status":true,"data":{"ip":"8.8.8.8","city":"Mountain View"}}' } },
  { name: 'Weather', description: 'Get current weather for any city', method: 'GET', endpoint: '/api/tools/weather', category: 'INFO', tags: ['weather', 'cuaca'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'city', type: 'query', required: true, description: 'City name' }], example: { request: 'GET /api/tools/weather?city=Jakarta', response: '{"status":true,"data":{"city":"Jakarta","temperature":{"celsius":"30"}}}' } },
  { name: 'News Search', description: 'Search latest news articles', method: 'GET', endpoint: '/api/tools/news', category: 'INFO', tags: ['news', 'berita'], cost: 2, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'q', type: 'query', required: false, description: 'Query (default: technology)' }], example: { request: 'GET /api/tools/news?q=AI', response: '{"status":true,"data":{"results":[{"title":"..."}]}}' } },
  { name: 'Dictionary', description: 'Get word definitions', method: 'GET', endpoint: '/api/tools/definition', category: 'INFO', tags: ['dictionary', 'kamus'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'word', type: 'query', required: true, description: 'Word to define' }], example: { request: 'GET /api/tools/definition?word=serendipity', response: '{"status":true,"data":{"word":"serendipity","meanings":[...]}}' } },
  { name: 'KBBI Dictionary', description: 'Indonesian dictionary (KBBI)', method: 'GET', endpoint: '/api/tools/kbbi', category: 'INFO', tags: ['kbbi', 'kamus', 'indonesia'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'word', type: 'query', required: true, description: 'Indonesian word' }], example: { request: 'GET /api/tools/kbbi?word=baik', response: '{"status":true,"data":{"definitions":[...]}}' } },
  { name: 'Currency Converter', description: 'Convert between currencies', method: 'GET', endpoint: '/api/tools/currency', category: 'INFO', tags: ['currency', 'money', 'forex'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'from', type: 'query', required: false, description: 'Source (default: USD)' }, { name: 'to', type: 'query', required: false, description: 'Target (default: IDR)' }, { name: 'amount', type: 'query', required: false, description: 'Amount (default: 1)' }], example: { request: 'GET /api/tools/currency?from=USD&to=IDR&amount=100', response: '{"status":true,"data":{"rate":15000,"result":1500000}}' } },
  { name: 'Timezone', description: 'Get current time in any timezone', method: 'GET', endpoint: '/api/tools/timezone', category: 'INFO', tags: ['timezone', 'time'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'tz', type: 'query', required: false, description: 'Timezone (default: Asia/Jakarta)' }], example: { request: 'GET /api/tools/timezone?tz=America/New_York', response: '{"status":true,"data":{"datetime":"2024-01-15 10:30:00"}}' } },
  { name: 'Crypto Price', description: 'Get cryptocurrency prices', method: 'GET', endpoint: '/api/tools/crypto', category: 'INFO', tags: ['crypto', 'bitcoin', 'ethereum'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'coin', type: 'query', required: false, description: 'Coin name (default: bitcoin)' }], example: { request: 'GET /api/tools/crypto?coin=bitcoin', response: '{"status":true,"data":{"price":{"usd":43000}}}' } },
  { name: 'Country Info', description: 'Get country information', method: 'GET', endpoint: '/api/tools/country', category: 'INFO', tags: ['country', 'negara'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'q', type: 'query', required: true, description: 'Country name' }], example: { request: 'GET /api/tools/country?q=indonesia', response: '{"status":true,"data":{"name":"Indonesia","capital":"Jakarta"}}' } },
  { name: 'Air Quality', description: 'Get air pollution data', method: 'GET', endpoint: '/api/tools/pollution', category: 'INFO', tags: ['pollution', 'air', 'aqi'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'lat', type: 'query', required: true, description: 'Latitude' }, { name: 'lon', type: 'query', required: true, description: 'Longitude' }], example: { request: 'GET /api/tools/pollution?lat=-6.2&lon=106.8', response: '{"status":true,"data":{"aqi":75,"level":"Moderate"}}' } },
  { name: 'NASA Space', description: 'NASA Astronomy Picture of the Day', method: 'GET', endpoint: '/api/tools/space', category: 'INFO', tags: ['nasa', 'space', 'apod'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'category', type: 'query', required: false, description: 'apod | rover' }], example: { request: 'GET /api/tools/space?category=apod', response: '{"status":true,"data":{"title":"...","url":"https://..."}}' } },
  { name: 'COVID Stats', description: 'Get COVID-19 statistics', method: 'GET', endpoint: '/api/tools/covid', category: 'INFO', tags: ['covid', 'corona'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'country', type: 'query', required: false, description: 'Country or "all"' }], example: { request: 'GET /api/tools/covid?country=indonesia', response: '{"status":true,"data":{"cases":6700000}}' } },
  { name: 'Steam Game', description: 'Search games on Steam', method: 'GET', endpoint: '/api/tools/steam', category: 'INFO', tags: ['steam', 'game'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'q', type: 'query', required: true, description: 'Game name' }], example: { request: 'GET /api/tools/steam?q=counter+strike', response: '{"status":true,"data":{"results":[{"name":"CS2"}]}}' } },

  { name: 'GitHub Profile', description: 'Get GitHub user profile', method: 'GET', endpoint: '/api/tools/github', category: 'DATA', tags: ['github', 'git', 'profile'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'user', type: 'query', required: true, description: 'GitHub username' }], example: { request: 'GET /api/tools/github?user=torvalds', response: '{"status":true,"data":{"username":"torvalds","repos":7}}' } },
  { name: 'GitHub Repos', description: 'Search GitHub repositories', method: 'GET', endpoint: '/api/tools/gh-repo', category: 'DATA', tags: ['github', 'repo'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'q', type: 'query', required: true, description: 'Search query' }], example: { request: 'GET /api/tools/gh-repo?q=nextjs', response: '{"status":true,"data":{"results":[{"name":"vercel/next.js"}]}}' } },
  { name: 'NPM Search', description: 'Search npm packages', method: 'GET', endpoint: '/api/tools/npm', category: 'DATA', tags: ['npm', 'package', 'node'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'q', type: 'query', required: true, description: 'Package name' }], example: { request: 'GET /api/tools/npm?q=express', response: '{"status":true,"data":{"results":[{"name":"express"}]}}' } },
  { name: 'Random User', description: 'Generate random user data', method: 'GET', endpoint: '/api/tools/random-user', category: 'DATA', tags: ['random', 'user', 'fake'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'count', type: 'query', required: false, description: 'Count (max 10)' }], example: { request: 'GET /api/tools/random-user?count=3', response: '{"status":true,"data":{"results":[{"name":{...}}]}}' } },
  { name: 'Random Facts', description: 'Get random fun facts', method: 'GET', endpoint: '/api/tools/random-facts', category: 'DATA', tags: ['random', 'facts'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'count', type: 'query', required: false, description: 'Count (max 10)' }], example: { request: 'GET /api/tools/random-facts?count=3', response: '{"status":true,"data":{"facts":["..."]}}' } },
  { name: 'Trivia', description: 'Get trivia questions', method: 'GET', endpoint: '/api/tools/trivia', category: 'DATA', tags: ['trivia', 'quiz'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'count', type: 'query', required: false, description: 'Count (max 10)' }], example: { request: 'GET /api/tools/trivia?count=5', response: '{"status":true,"data":{"questions":[{"question":"..."}]}}' } },
  { name: 'Jokes', description: 'Get random jokes', method: 'GET', endpoint: '/api/tools/jokes', category: 'DATA', tags: ['jokes', 'humor'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'category', type: 'query', required: false, description: 'Category (default: Programming)' }], example: { request: 'GET /api/tools/jokes?category=Programming', response: '{"status":true,"data":{"jokes":[{"setup":"...","punchline":"..."}]}}' } },
  { name: 'Dad Joke', description: 'Get a random dad joke', method: 'GET', endpoint: '/api/tools/dadjoke', category: 'DATA', tags: ['joke', 'dad'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }], example: { request: 'GET /api/tools/dadjoke', response: '{"status":true,"data":{"joke":"I\'m afraid for the calendar..."}}' } },
  { name: 'Quotes', description: 'Get inspirational quotes', method: 'GET', endpoint: '/api/tools/quotes', category: 'DATA', tags: ['quotes', 'motivation'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'count', type: 'query', required: false, description: 'Count (max 5)' }], example: { request: 'GET /api/tools/quotes?count=3', response: '{"status":true,"data":{"quotes":[{"content":"..."}]}}' } },
  { name: 'Inspire Quote', description: 'Get random inspirational quote', method: 'GET', endpoint: '/api/tools/inspire', category: 'DATA', tags: ['inspire', 'quote'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }], example: { request: 'GET /api/tools/inspire', response: '{"status":true,"data":{"content":"...","author":"..."}}' } },
  { name: 'Random Cat', description: 'Get random cat images', method: 'GET', endpoint: '/api/tools/cat', category: 'DATA', tags: ['cat', 'kucing', 'animal'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'count', type: 'query', required: false, description: 'Count (max 5)' }], example: { request: 'GET /api/tools/cat?count=3', response: '{"status":true,"data":{"cats":[{"url":"https://..."}]}}' } },
  { name: 'Random Dog', description: 'Get random dog images', method: 'GET', endpoint: '/api/tools/dog', category: 'DATA', tags: ['dog', 'anjing', 'animal'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'count', type: 'query', required: false, description: 'Count (max 5)' }], example: { request: 'GET /api/tools/dog?count=3', response: '{"status":true,"data":{"dogs":[{"url":"https://..."}]}}' } },
  { name: 'Random Meme', description: 'Get random memes', method: 'GET', endpoint: '/api/tools/meme', category: 'DATA', tags: ['meme', 'reddit', 'funny'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'count', type: 'query', required: false, description: 'Count (max 5)' }], example: { request: 'GET /api/tools/meme?count=3', response: '{"status":true,"data":{"memes":[{"title":"..."}]}}' } },
  { name: 'Recipe Search', description: 'Search recipes', method: 'GET', endpoint: '/api/tools/recipe', category: 'DATA', tags: ['recipe', 'food', 'resep'], cost: 2, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'q', type: 'query', required: true, description: 'Dish name' }], example: { request: 'GET /api/tools/recipe?q=nasi+goreng', response: '{"status":true,"data":{"results":[{"title":"Nasi Goreng"}]}}' } },

  { name: 'QR Code', description: 'Generate QR code', method: 'GET', endpoint: '/api/tools/qrcode', category: 'TOOLS', tags: ['qr', 'qrcode', 'barcode'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'text', type: 'query', required: true, description: 'Text or URL' }, { name: 'size', type: 'query', required: false, description: 'Size (default: 300)' }], example: { request: 'GET /api/tools/qrcode?text=https://google.com', response: '{"status":true,"data":{"qr":"https://api.qrserver.com/..."}}' } },
  { name: 'URL Shortener', description: 'Shorten any URL', method: 'GET', endpoint: '/api/tools/shorturl', category: 'TOOLS', tags: ['short', 'url', 'link'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'url', type: 'query', required: true, description: 'URL to shorten' }], example: { request: 'GET /api/tools/shorturl?url=https://google.com', response: '{"status":true,"data":{"short":"https://cleanuri.com/..."}}' } },
  { name: 'Translate', description: 'Translate text to any language', method: 'GET', endpoint: '/api/tools/translate', category: 'TOOLS', tags: ['translate', 'bahasa'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'text', type: 'query', required: true, description: 'Text to translate' }, { name: 'to', type: 'query', required: false, description: 'Target (default: en)' }], example: { request: 'GET /api/tools/translate?text=Halo&to=en', response: '{"status":true,"data":{"translated":"Hello"}}' } },
  { name: 'YouTube Search', description: 'Search YouTube videos', method: 'GET', endpoint: '/api/tools/yt-search', category: 'TOOLS', tags: ['youtube', 'yt', 'search'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'q', type: 'query', required: true, description: 'Search query' }], example: { request: 'GET /api/tools/yt-search?q=nodejs', response: '{"status":true,"data":{"results":[{"title":"..."}]}}' } },
]

export const categoryColors: Record<string, string> = {
  SEND: 'text-blue-400',
  TEXT: 'text-green-400',
  IMAGE: 'text-pink-400',
  DOWNLOADER: 'text-red-400',
  ANIME: 'text-purple-400',
  MEDIA: 'text-yellow-400',
  INFO: 'text-cyan-400',
  DATA: 'text-orange-400',
  TOOLS: 'text-slate-300'
}
