export interface ApiEndpoint {
  name: string
  description: string
  method: 'GET' | 'POST'
  endpoint: string
  category: string
  tags: string[]
  cost: number
  params: { name: string; type: string; required: boolean; description: string }[]
  body?: { name: string; type: string; required: boolean; description: string }[]
  example: { request: string; response: string }
}

export const endpoints: ApiEndpoint[] = [
  { name: 'Text to MP3', description: 'Convert text to downloadable MP3 audio', method: 'GET', endpoint: '/api/tools/text-to-mp3', category: 'TEXT', tags: ['tts', 'mp3', 'audio'], cost: 2, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'text', type: 'query', required: true, description: 'Text to convert (max 5000)' }, { name: 'lang', type: 'query', required: false, description: 'Language code (default: id)' }], example: { request: 'GET /api/tools/text-to-mp3?text=Halo', response: '{"status":true,"data":{"downloadUrl":"https://..."}}' } },
  { name: 'Lorem Ipsum', description: 'Generate placeholder text', method: 'GET', endpoint: '/api/tools/lorem-ipsum', category: 'TEXT', tags: ['lorem', 'placeholder'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'paragraphs', type: 'query', required: false, description: 'Number (default 3, max 20)' }], example: { request: 'GET /api/tools/lorem-ipsum?paragraphs=2', response: '{"status":true,"data":{"text":"Lorem ipsum..."}}' } },
  { name: 'Password Generator', description: 'Generate secure random passwords', method: 'GET', endpoint: '/api/tools/password-gen', category: 'TEXT', tags: ['password', 'random'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'length', type: 'query', required: false, description: 'Length 4-128 (default: 16)' }, { name: 'count', type: 'query', required: false, description: 'Count max 10' }], example: { request: 'GET /api/tools/password-gen?length=20', response: '{"status":true,"data":{"passwords":["abc123..."]}}' } },

  { name: 'Placeholder Image', description: 'Generate placeholder images', method: 'GET', endpoint: '/api/tools/placeholder', category: 'IMAGE', tags: ['placeholder', 'image'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'width', type: 'query', required: false, description: 'Width (default: 300)' }, { name: 'height', type: 'query', required: false, description: 'Height (default: 200)' }, { name: 'text', type: 'query', required: false, description: 'Text on image' }], example: { request: 'GET /api/tools/placeholder?width=400&height=300', response: '{"status":true,"data":{"url":"https://placehold.co/..."}}' } },
  { name: 'Avatar Generator', description: 'Generate avatar from initials', method: 'GET', endpoint: '/api/tools/avatar', category: 'IMAGE', tags: ['avatar', 'profile'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'name', type: 'query', required: false, description: 'Name for initials' }, { name: 'size', type: 'query', required: false, description: 'Size (default: 128)' }], example: { request: 'GET /api/tools/avatar?name=John+Doe', response: '{"status":true,"data":{"url":"https://ui-avatars.com/api/..."}}' } },
  { name: 'Color Info', description: 'Get color details from hex code', method: 'GET', endpoint: '/api/tools/color', category: 'IMAGE', tags: ['color', 'hex', 'rgb'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'hex', type: 'query', required: false, description: 'Hex color (default: #3b82f6)' }], example: { request: 'GET /api/tools/color?hex=#ff0000', response: '{"status":true,"data":{"hex":"#ff0000","rgb":{"r":255,"g":0,"b":0}}}' } },

  { name: 'YouTube Downloader', description: 'Download YouTube video as MP3/MP4', method: 'GET', endpoint: '/api/tools/ytdl', category: 'DOWNLOADER', tags: ['youtube', 'ytdl', 'mp3', 'mp4'], cost: 3, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'url', type: 'query', required: true, description: 'YouTube URL' }, { name: 'format', type: 'query', required: false, description: 'mp3 | mp4 (default: mp4)' }, { name: 'quality', type: 'query', required: false, description: '360/480/720/1080' }], example: { request: 'GET /api/tools/ytdl?url=https://youtu.be/xxx&format=mp3', response: '{"status":true,"data":{"downloadUrl":"https://...mp3"}}' } },
  { name: 'Instagram Downloader', description: 'Download Instagram posts/reels', method: 'GET', endpoint: '/api/tools/igdl', category: 'DOWNLOADER', tags: ['instagram', 'ig', 'download'], cost: 3, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'url', type: 'query', required: true, description: 'Instagram post/reel URL' }], example: { request: 'GET /api/tools/igdl?url=https://instagram.com/p/xxx', response: '{"status":true,"data":{"downloadUrl":"https://..."}}' } },
  { name: 'Twitter/X Downloader', description: 'Download Twitter/X videos and images', method: 'GET', endpoint: '/api/tools/xdl', category: 'DOWNLOADER', tags: ['twitter', 'x', 'tweet'], cost: 3, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'url', type: 'query', required: true, description: 'Twitter/X tweet URL' }], example: { request: 'GET /api/tools/xdl?url=https://twitter.com/user/status/xxx', response: '{"status":true,"data":{"downloadUrl":"https://..."}}' } },
  { name: 'Facebook Downloader', description: 'Download Facebook videos', method: 'GET', endpoint: '/api/tools/fbdl', category: 'DOWNLOADER', tags: ['facebook', 'fb', 'download'], cost: 3, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'url', type: 'query', required: true, description: 'Facebook video URL' }], example: { request: 'GET /api/tools/fbdl?url=https://facebook.com/watch?v=xxx', response: '{"status":true,"data":{"downloadUrl":"https://..."}}' } },

  { name: 'Anime Search', description: 'Search anime from MyAnimeList', method: 'GET', endpoint: '/api/tools/anime', category: 'ANIME', tags: ['anime', 'manga', 'mal'], cost: 2, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'q', type: 'query', required: true, description: 'Anime title' }], example: { request: 'GET /api/tools/anime?q=naruto', response: '{"status":true,"data":{"results":[{"title":"Naruto"}]}}' } },
  { name: 'Anime Detail', description: 'Get detailed anime info by MAL ID', method: 'GET', endpoint: '/api/tools/anime-detail', category: 'ANIME', tags: ['anime', 'detail'], cost: 2, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'id', type: 'query', required: true, description: 'MyAnimeList ID' }], example: { request: 'GET /api/tools/anime-detail?id=1', response: '{"status":true,"data":{"title":"Cowboy Bebop"}}' } },
  { name: 'Manga Search', description: 'Search manga from MyAnimeList', method: 'GET', endpoint: '/api/tools/manga', category: 'ANIME', tags: ['manga', 'comic'], cost: 2, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'q', type: 'query', required: true, description: 'Manga title' }], example: { request: 'GET /api/tools/manga?q=one+piece', response: '{"status":true,"data":{"results":[{"title":"One Piece"}]}}' } },
  { name: 'Character Search', description: 'Search anime characters', method: 'GET', endpoint: '/api/tools/character', category: 'ANIME', tags: ['character'], cost: 2, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'q', type: 'query', required: true, description: 'Character name' }], example: { request: 'GET /api/tools/character?q=naruto', response: '{"status":true,"data":{"results":[{"name":"Naruto"}]}}' } },
  { name: 'Waifu Image', description: 'Get random anime/waifu images from waifu.im', method: 'GET', endpoint: '/api/tools/waifu-im', category: 'ANIME', tags: ['waifu', 'anime', 'neko'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'tags', type: 'query', required: false, description: 'waifu/neko/megumin/shinobu/etc' }, { name: 'limit', type: 'query', required: false, description: 'Number of images (1-10)' }], example: { request: 'GET /api/tools/waifu-im?tags=neko', response: '{"status":true,"data":{"count":1,"images":[{"url":"https://..."}]}}' } },

  { name: 'Lyrics', description: 'Search song lyrics', method: 'GET', endpoint: '/api/tools/lyrics', category: 'MEDIA', tags: ['lyrics', 'lirik', 'song'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'q', type: 'query', required: true, description: 'Song title' }], example: { request: 'GET /api/tools/lyrics?q=shape+of+you', response: '{"status":true,"data":{"title":"Shape of You","lyrics":"..."}}' } },
  { name: 'Spotify Info', description: 'Get Spotify track/album info', method: 'GET', endpoint: '/api/tools/spotify', category: 'MEDIA', tags: ['spotify', 'music'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'url', type: 'query', required: true, description: 'Spotify URL' }], example: { request: 'GET /api/tools/spotify?url=https://open.spotify.com/track/xxx', response: '{"status":true,"data":{"title":"Shape of You"}}' } },
  { name: 'Movie Search', description: 'Search movies and TV shows', method: 'GET', endpoint: '/api/tools/movie', category: 'MEDIA', tags: ['movie', 'film', 'imdb'], cost: 2, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'q', type: 'query', required: true, description: 'Movie title' }], example: { request: 'GET /api/tools/movie?q=inception', response: '{"status":true,"data":{"results":[{"title":"Inception"}]}}' } },
  { name: 'Book Search', description: 'Search books from Google Books', method: 'GET', endpoint: '/api/tools/book', category: 'MEDIA', tags: ['book', 'read'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'q', type: 'query', required: true, description: 'Book title or author' }], example: { request: 'GET /api/tools/book?q=atomic+habits', response: '{"status":true,"data":{"results":[{"title":"Atomic Habits"}]}}' } },

  { name: 'IP Lookup', description: 'Lookup geolocation for IP address', method: 'GET', endpoint: '/api/tools/ip-lookup', category: 'INFO', tags: ['ip', 'location', 'geo'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'ip', type: 'query', required: false, description: 'IP (empty = your IP)' }], example: { request: 'GET /api/tools/ip-lookup?ip=8.8.8.8', response: '{"status":true,"data":{"ip":"8.8.8.8","city":"Mountain View"}}' } },
  { name: 'Weather', description: 'Get current weather for any city', method: 'GET', endpoint: '/api/tools/weather', category: 'INFO', tags: ['weather', 'cuaca'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'city', type: 'query', required: true, description: 'City name' }], example: { request: 'GET /api/tools/weather?city=Jakarta', response: '{"status":true,"data":{"city":"Jakarta","temperature":{"celsius":"30"}}}' } },
  { name: 'News Search', description: 'Search latest news articles', method: 'GET', endpoint: '/api/tools/news', category: 'INFO', tags: ['news', 'berita'], cost: 2, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'q', type: 'query', required: false, description: 'Query (default: technology)' }], example: { request: 'GET /api/tools/news?q=AI', response: '{"status":true,"data":{"results":[{"title":"..."}]}}' } },
  { name: 'Dictionary', description: 'Get word definitions', method: 'GET', endpoint: '/api/tools/definition', category: 'INFO', tags: ['dictionary', 'kamus'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'word', type: 'query', required: true, description: 'Word to define' }], example: { request: 'GET /api/tools/definition?word=serendipity', response: '{"status":true,"data":{"word":"serendipity","meanings":[...]}}' } },
  { name: 'KBBI Dictionary', description: 'Indonesian dictionary (KBBI)', method: 'GET', endpoint: '/api/tools/kbbi', category: 'INFO', tags: ['kbbi', 'kamus', 'indonesia'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'word', type: 'query', required: true, description: 'Indonesian word' }], example: { request: 'GET /api/tools/kbbi?word=baik', response: '{"status":true,"data":{"definitions":[...]}}' } },
  { name: 'Currency Converter', description: 'Convert between currencies', method: 'GET', endpoint: '/api/tools/currency', category: 'INFO', tags: ['currency', 'money', 'forex'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'from', type: 'query', required: false, description: 'Source (default: USD)' }, { name: 'to', type: 'query', required: false, description: 'Target (default: IDR)' }, { name: 'amount', type: 'query', required: false, description: 'Amount (default: 1)' }], example: { request: 'GET /api/tools/currency?from=USD&to=IDR&amount=100', response: '{"status":true,"data":{"rate":15000,"result":1500000}}' } },
  { name: 'Timezone', description: 'Get current time in any timezone', method: 'GET', endpoint: '/api/tools/timezone', category: 'INFO', tags: ['timezone', 'time'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'tz', type: 'query', required: false, description: 'Timezone (default: Asia/Jakarta)' }], example: { request: 'GET /api/tools/timezone?tz=America/New_York', response: '{"status":true,"data":{"datetime":"2024-01-15 10:30:00"}}' } },
  { name: 'Crypto Price', description: 'Get cryptocurrency prices', method: 'GET', endpoint: '/api/tools/crypto', category: 'INFO', tags: ['crypto', 'bitcoin', 'ethereum'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'coin', type: 'query', required: false, description: 'Coin name (default: bitcoin)' }], example: { request: 'GET /api/tools/crypto?coin=bitcoin', response: '{"status":true,"data":{"price":{"usd":43000}}}' } },
  { name: 'Country Info', description: 'Get country information', method: 'GET', endpoint: '/api/tools/country', category: 'INFO', tags: ['country', 'negara'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'q', type: 'query', required: true, description: 'Country name' }], example: { request: 'GET /api/tools/country?q=indonesia', response: '{"status":true,"data":{"name":"Indonesia","capital":"Jakarta"}}' } },
  { name: 'Air Quality', description: 'Get air pollution data', method: 'GET', endpoint: '/api/tools/pollution', category: 'INFO', tags: ['pollution', 'air', 'aqi'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'lat', type: 'query', required: true, description: 'Latitude' }, { name: 'lon', type: 'query', required: true, description: 'Longitude' }], example: { request: 'GET /api/tools/pollution?lat=-6.2&lon=106.8', response: '{"status":true,"data":{"aqi":75,"level":"Moderate"}}' } },
  { name: 'NASA Space', description: 'NASA Astronomy Picture of the Day', method: 'GET', endpoint: '/api/tools/space', category: 'INFO', tags: ['nasa', 'space', 'apod'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'category', type: 'query', required: false, description: 'apod | rover' }], example: { request: 'GET /api/tools/space?category=apod', response: '{"status":true,"data":{"title":"...","url":"https://..."}}' } },
  { name: 'COVID Stats', description: 'Get COVID-19 statistics', method: 'GET', endpoint: '/api/tools/covid', category: 'INFO', tags: ['covid', 'corona'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'country', type: 'query', required: false, description: 'Country or "all"' }], example: { request: 'GET /api/tools/covid?country=indonesia', response: '{"status":true,"data":{"cases":6700000}}' } },
  { name: 'Steam Game', description: 'Search games on Steam', method: 'GET', endpoint: '/api/tools/steam', category: 'INFO', tags: ['steam', 'game'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'q', type: 'query', required: true, description: 'Game name' }], example: { request: 'GET /api/tools/steam?q=counter+strike', response: '{"status":true,"data":{"results":[{"name":"CS2"}]}}' } },

  { name: 'GitHub Profile', description: 'Get GitHub user profile', method: 'GET', endpoint: '/api/tools/github', category: 'DATA', tags: ['github', 'git', 'profile'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'user', type: 'query', required: true, description: 'GitHub username' }], example: { request: 'GET /api/tools/github?user=torvalds', response: '{"status":true,"data":{"username":"torvalds","repos":7}}' } },
  { name: 'GitHub Repos', description: 'Search GitHub repositories', method: 'GET', endpoint: '/api/tools/gh-repo', category: 'DATA', tags: ['github', 'repo'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'q', type: 'query', required: true, description: 'Search query' }], example: { request: 'GET /api/tools/gh-repo?q=nextjs', response: '{"status":true,"data":{"results":[{"name":"vercel/next.js"}]}}' } },
  { name: 'NPM Search', description: 'Search npm packages', method: 'GET', endpoint: '/api/tools/npm', category: 'DATA', tags: ['npm', 'package', 'node'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'q', type: 'query', required: true, description: 'Package name' }], example: { request: 'GET /api/tools/npm?q=express', response: '{"status":true,"data":{"results":[{"name":"express"}]}}' } },
  { name: 'Random User', description: 'Generate random user data', method: 'GET', endpoint: '/api/tools/random-user', category: 'DATA', tags: ['random', 'user', 'fake'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'count', type: 'query', required: false, description: 'Count (max 10)' }], example: { request: 'GET /api/tools/random-user?count=3', response: '{"status":true,"data":{"results":[{"name":{...}}]}}' } },
  { name: 'Random Facts', description: 'Get random fun facts', method: 'GET', endpoint: '/api/tools/random-facts', category: 'DATA', tags: ['random', 'facts'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'count', type: 'query', required: false, description: 'Count (max 10)' }], example: { request: 'GET /api/tools/random-facts?count=3', response: '{"status":true,"data":{"facts":["..."]}}' } },
  { name: 'Trivia', description: 'Get trivia questions', method: 'GET', endpoint: '/api/tools/trivia', category: 'DATA', tags: ['trivia', 'quiz'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'count', type: 'query', required: false, description: 'Count (max 10)' }], example: { request: 'GET /api/tools/trivia?count=5', response: '{"status":true,"data":{"questions":[{"question":"..."}]}}' } },
  { name: 'Jokes', description: 'Get random jokes', method: 'GET', endpoint: '/api/tools/jokes', category: 'DATA', tags: ['jokes', 'humor'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'category', type: 'query', required: false, description: 'Category (default: Programming)' }], example: { request: 'GET /api/tools/jokes?category=Programming', response: '{"status":true,"data":{"jokes":[{"setup":"...","punchline":"..."}]}}' } },
  { name: 'Dad Joke', description: 'Get a random dad joke', method: 'GET', endpoint: '/api/tools/dadjoke', category: 'DATA', tags: ['joke', 'dad'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }], example: { request: 'GET /api/tools/dadjoke', response: '{"status":true,"data":{"joke":"I\'m afraid for the calendar..."}}' } },
  { name: 'Quotes', description: 'Get inspirational quotes', method: 'GET', endpoint: '/api/tools/quotes', category: 'DATA', tags: ['quotes', 'motivation'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'count', type: 'query', required: false, description: 'Count (max 5)' }], example: { request: 'GET /api/tools/quotes?count=3', response: '{"status":true,"data":{"quotes":[{"content":"..."}]}}' } },
  { name: 'Inspire Quote', description: 'Get random inspirational quote', method: 'GET', endpoint: '/api/tools/inspire', category: 'DATA', tags: ['inspire', 'quote'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }], example: { request: 'GET /api/tools/inspire', response: '{"status":true,"data":{"content":"...","author":"..."}}' } },
  { name: 'Random Cat', description: 'Get random cat images', method: 'GET', endpoint: '/api/tools/cat', category: 'DATA', tags: ['cat', 'kucing', 'animal'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'count', type: 'query', required: false, description: 'Count (max 5)' }], example: { request: 'GET /api/tools/cat?count=3', response: '{"status":true,"data":{"cats":[{"url":"https://..."}]}}' } },
  { name: 'Random Dog', description: 'Get random dog images', method: 'GET', endpoint: '/api/tools/dog', category: 'DATA', tags: ['dog', 'anjing', 'animal'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'count', type: 'query', required: false, description: 'Count (max 5)' }], example: { request: 'GET /api/tools/dog?count=3', response: '{"status":true,"data":{"dogs":[{"url":"https://..."}]}}' } },
  { name: 'Random Meme', description: 'Get random memes', method: 'GET', endpoint: '/api/tools/meme', category: 'DATA', tags: ['meme', 'reddit', 'funny'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'count', type: 'query', required: false, description: 'Count (max 5)' }], example: { request: 'GET /api/tools/meme?count=3', response: '{"status":true,"data":{"memes":[{"title":"..."}]}}' } },
  { name: 'Recipe Search', description: 'Search recipes', method: 'GET', endpoint: '/api/tools/recipe', category: 'DATA', tags: ['recipe', 'food', 'resep'], cost: 2, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'q', type: 'query', required: true, description: 'Dish name' }], example: { request: 'GET /api/tools/recipe?q=nasi+goreng', response: '{"status":true,"data":{"results":[{"title":"Nasi Goreng"}]}}' } },

  { name: 'QR Code', description: 'Generate QR code', method: 'GET', endpoint: '/api/tools/qrcode', category: 'TOOLS', tags: ['qr', 'qrcode', 'barcode'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'text', type: 'query', required: true, description: 'Text or URL' }, { name: 'size', type: 'query', required: false, description: 'Size (default: 300)' }], example: { request: 'GET /api/tools/qrcode?text=https://google.com', response: '{"status":true,"data":{"qr":"https://api.qrserver.com/..."}}' } },
  { name: 'URL Shortener', description: 'Shorten any URL', method: 'GET', endpoint: '/api/tools/shorturl', category: 'TOOLS', tags: ['short', 'url', 'link'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'url', type: 'query', required: true, description: 'URL to shorten' }], example: { request: 'GET /api/tools/shorturl?url=https://google.com', response: '{"status":true,"data":{"short":"https://cleanuri.com/..."}}' } },
  { name: 'Translate', description: 'Translate text to any language', method: 'GET', endpoint: '/api/tools/translate', category: 'TOOLS', tags: ['translate', 'bahasa'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'text', type: 'query', required: true, description: 'Text to translate' }, { name: 'to', type: 'query', required: false, description: 'Target (default: en)' }], example: { request: 'GET /api/tools/translate?text=Halo&to=en', response: '{"status":true,"data":{"translated":"Hello"}}' } },
  { name: 'YouTube Search', description: 'Search YouTube videos', method: 'GET', endpoint: '/api/tools/yt-search', category: 'TOOLS', tags: ['youtube', 'yt', 'search'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'q', type: 'query', required: true, description: 'Search query' }], example: { request: 'GET /api/tools/yt-search?q=nodejs', response: '{"status":true,"data":{"results":[{"title":"..."}]}}' } },

  { name: 'Top Anime', description: 'Get top ranked anime', method: 'GET', endpoint: '/api/tools/top-anime', category: 'ANIME', tags: ['top', 'anime'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'filter', type: 'query', required: false, description: 'Filter type' }, { name: 'limit', type: 'query', required: false, description: 'Limit' }], example: { request: 'GET /api/tools/top-anime?filter=bypopularity', response: '{"status":true,"data":{"results":[...]}}' } },
  { name: 'Anime Episodes', description: 'Get episode list for an anime', method: 'GET', endpoint: '/api/tools/anime-episode', category: 'ANIME', tags: ['anime', 'episode'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'id', type: 'query', required: true, description: 'MAL anime ID' }, { name: 'page', type: 'query', required: false, description: 'Page number' }], example: { request: 'GET /api/tools/anime-episode?id=5114', response: '{"status":true,"data":{"results":[...]}}' } },
  { name: 'Anime Genres', description: 'Get all anime genres', method: 'GET', endpoint: '/api/tools/anime-genres', category: 'ANIME', tags: ['anime', 'genres'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }], example: { request: 'GET /api/tools/anime-genres', response: '{"status":true,"data":{"results":[...]}}' } },
  { name: 'Character Detail', description: 'Get detailed character info', method: 'GET', endpoint: '/api/tools/character-detail', category: 'ANIME', tags: ['character', 'detail'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'id', type: 'query', required: true, description: 'MAL character ID' }], example: { request: 'GET /api/tools/character-detail?id=1', response: '{"status":true,"data":{"name":"Goku",...}}' } },
  { name: 'Manga Chapters', description: 'Get manga chapter info', method: 'GET', endpoint: '/api/tools/manga-chapters', category: 'ANIME', tags: ['manga', 'chapters'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'id', type: 'query', required: true, description: 'MAL manga ID' }], example: { request: 'GET /api/tools/manga-chapters?id=13', response: '{"status":true,"data":{"title":"One Piece",...}}' } },
  { name: 'Manga Detail', description: 'Get detailed manga info', method: 'GET', endpoint: '/api/tools/manga-detail', category: 'ANIME', tags: ['manga', 'detail'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'id', type: 'query', required: true, description: 'MAL manga ID' }], example: { request: 'GET /api/tools/manga-detail?id=13', response: '{"status":true,"data":{"title":"One Piece",...}}' } },
  { name: 'Manga Genres', description: 'Get all manga genres', method: 'GET', endpoint: '/api/tools/manga-genres', category: 'ANIME', tags: ['manga', 'genres'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }], example: { request: 'GET /api/tools/manga-genres', response: '{"status":true,"data":{"results":[...]}}' } },

  { name: 'Crate.io Search', description: 'Search Rust crates', method: 'GET', endpoint: '/api/tools/crates-io', category: 'DATA', tags: ['crates', 'rust'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'q', type: 'query', required: true, description: 'Search query' }], example: { request: 'GET /api/tools/crates-io?q=serde', response: '{"status":true,"data":{"crates":[...]}}' } },
  { name: 'Dev.to Search', description: 'Search dev.to articles', method: 'GET', endpoint: '/api/tools/devto-search', category: 'DATA', tags: ['devto', 'articles'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'q', type: 'query', required: true, description: 'Tag to search' }], example: { request: 'GET /api/tools/devto-search?q=javascript', response: '{"status":true,"data":{"articles":[...]}}' } },
  { name: 'Docker Hub', description: 'Search Docker Hub images', method: 'GET', endpoint: '/api/tools/docker-hub', category: 'DATA', tags: ['docker', 'container'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'q', type: 'query', required: true, description: 'Search query' }], example: { request: 'GET /api/tools/docker-hub?q=nginx', response: '{"status":true,"data":{"results":[...]}}' } },
  { name: 'GitHub Trending', description: 'Get trending GitHub repos', method: 'GET', endpoint: '/api/tools/github-trending', category: 'DATA', tags: ['github', 'trending'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'language', type: 'query', required: false, description: 'Language filter' }, { name: 'since', type: 'query', required: false, description: 'daily/weekly/monthly' }], example: { request: 'GET /api/tools/github-trending?language=typescript', response: '{"status":true,"data":{"repos":[...]}}' } },
  { name: 'Hacker News', description: 'Get Hacker News stories', method: 'GET', endpoint: '/api/tools/hacker-news', category: 'DATA', tags: ['hacker', 'news'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'limit', type: 'query', required: false, description: 'Max items' }], example: { request: 'GET /api/tools/hacker-news?limit=10', response: '{"status":true,"data":{"stories":[...]}}' } },
  { name: 'NPM Trending', description: 'Get trending npm packages', method: 'GET', endpoint: '/api/tools/npm-trending', category: 'DATA', tags: ['npm', 'trending'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }], example: { request: 'GET /api/tools/npm-trending', response: '{"status":true,"data":{"packages":[...]}}' } },
  { name: 'Product Hunt', description: 'Get Product Hunt launches', method: 'GET', endpoint: '/api/tools/product-hunt', category: 'DATA', tags: ['product', 'hunt'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }], example: { request: 'GET /api/tools/product-hunt', response: '{"status":true,"data":{"products":[...]}}' } },
  { name: 'Random Advice', description: 'Get random advice', method: 'GET', endpoint: '/api/tools/random-advice', category: 'DATA', tags: ['random', 'advice'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }], example: { request: 'GET /api/tools/random-advice', response: '{"status":true,"data":{"advice":"..."}}' } },
  { name: 'Random Bunny', description: 'Get random bunny images', method: 'GET', endpoint: '/api/tools/random-bunny', category: 'DATA', tags: ['random', 'bunny'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }], example: { request: 'GET /api/tools/random-bunny', response: '{"status":true,"data":{"url":"https://..."}}' } },
  { name: 'Random Dog Pose', description: 'Get random dog images by pose', method: 'GET', endpoint: '/api/tools/random-dog-pose', category: 'DATA', tags: ['random', 'dog'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }], example: { request: 'GET /api/tools/random-dog-pose', response: '{"status":true,"data":{"url":"https://..."}}' } },
  { name: 'Random Fact', description: 'Get a random fun fact', method: 'GET', endpoint: '/api/tools/random-fact', category: 'DATA', tags: ['random', 'fact'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }], example: { request: 'GET /api/tools/random-fact', response: '{"status":true,"data":{"fact":"..."}}' } },
  { name: 'Random Fox', description: 'Get random fox images', method: 'GET', endpoint: '/api/tools/random-fox', category: 'DATA', tags: ['random', 'fox'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }], example: { request: 'GET /api/tools/random-fox', response: '{"status":true,"data":{"image":"https://..."}}' } },
  { name: 'Random Jokes', description: 'Get random jokes', method: 'GET', endpoint: '/api/tools/random-jokes', category: 'DATA', tags: ['random', 'jokes'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'count', type: 'query', required: false, description: 'Count' }], example: { request: 'GET /api/tools/random-jokes?count=3', response: '{"status":true,"data":{"jokes":[...]}}' } },
  { name: 'Random Pokemon', description: 'Get random Pokemon data', method: 'GET', endpoint: '/api/tools/random-pokemon', category: 'DATA', tags: ['random', 'pokemon'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'count', type: 'query', required: false, description: 'Count' }], example: { request: 'GET /api/tools/random-pokemon', response: '{"status":true,"data":{"pokemon":{...}}}' } },
  { name: 'Random Quotes', description: 'Get random quotes', method: 'GET', endpoint: '/api/tools/random-quotes', category: 'DATA', tags: ['random', 'quotes'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'count', type: 'query', required: false, description: 'Count' }], example: { request: 'GET /api/tools/random-quotes?count=3', response: '{"status":true,"data":{"quotes":[...]}}' } },
  { name: 'StackOverflow', description: 'Search StackOverflow questions', method: 'GET', endpoint: '/api/tools/stackoverflow', category: 'DATA', tags: ['stackoverflow', 'qa'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'q', type: 'query', required: true, description: 'Search query' }], example: { request: 'GET /api/tools/stackoverflow?q=nextjs', response: '{"status":true,"data":{"questions":[...]}}' } },

  { name: 'Bilibili Downloader', description: 'Download Bilibili videos', method: 'GET', endpoint: '/api/tools/bilibili-dl', category: 'DOWNLOADER', tags: ['bilibili', 'download'], cost: 3, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'url', type: 'query', required: true, description: 'Bilibili video URL' }], example: { request: 'GET /api/tools/bilibili-dl?url=https://bilibili.com/video/...', response: '{"status":true,"data":{"downloadUrl":"https://..."}}' } },
  { name: 'Dailymotion Downloader', description: 'Download Dailymotion videos', method: 'GET', endpoint: '/api/tools/dailymotion-dl', category: 'DOWNLOADER', tags: ['dailymotion', 'download'], cost: 3, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'url', type: 'query', required: true, description: 'Dailymotion URL' }], example: { request: 'GET /api/tools/dailymotion-dl?url=...', response: '{"status":true,"data":{"downloadUrl":"https://..."}}' } },
  { name: 'Pinterest Downloader', description: 'Download Pinterest images', method: 'GET', endpoint: '/api/tools/pinterest-dl', category: 'DOWNLOADER', tags: ['pinterest', 'download'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'url', type: 'query', required: true, description: 'Pinterest URL' }], example: { request: 'GET /api/tools/pinterest-dl?url=...', response: '{"status":true,"data":{"downloadUrl":"https://..."}}' } },
  { name: 'Reddit Downloader', description: 'Download Reddit videos', method: 'GET', endpoint: '/api/tools/reddit-dl', category: 'DOWNLOADER', tags: ['reddit', 'download'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'url', type: 'query', required: true, description: 'Reddit URL' }], example: { request: 'GET /api/tools/reddit-dl?url=...', response: '{"status":true,"data":{"downloadUrl":"https://..."}}' } },
  { name: 'SoundCloud Downloader', description: 'Download SoundCloud tracks', method: 'GET', endpoint: '/api/tools/soundcloud-dl', category: 'DOWNLOADER', tags: ['soundcloud', 'download'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'url', type: 'query', required: true, description: 'SoundCloud URL' }], example: { request: 'GET /api/tools/soundcloud-dl?url=...', response: '{"status":true,"data":{"downloadUrl":"https://..."}}' } },
  { name: 'Streamable Downloader', description: 'Download Streamable videos', method: 'GET', endpoint: '/api/tools/streamable-dl', category: 'DOWNLOADER', tags: ['streamable', 'download'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'url', type: 'query', required: true, description: 'Streamable URL' }], example: { request: 'GET /api/tools/streamable-dl?url=...', response: '{"status":true,"data":{"downloadUrl":"https://..."}}' } },
  { name: 'TikTok Alt', description: 'Download TikTok videos (alt)', method: 'GET', endpoint: '/api/tools/tiktok', category: 'DOWNLOADER', tags: ['tiktok', 'download'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'url', type: 'query', required: true, description: 'TikTok URL' }], example: { request: 'GET /api/tools/tiktok?url=...', response: '{"status":true,"data":{"downloadUrl":"https://..."}}' } },
  { name: 'Twitch Downloader', description: 'Download Twitch clips', method: 'GET', endpoint: '/api/tools/twitch-dl', category: 'DOWNLOADER', tags: ['twitch', 'download'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'url', type: 'query', required: true, description: 'Twitch URL' }], example: { request: 'GET /api/tools/twitch-dl?url=...', response: '{"status":true,"data":{"downloadUrl":"https://..."}}' } },
  { name: 'Vimeo Downloader', description: 'Download Vimeo videos', method: 'GET', endpoint: '/api/tools/vimeo-dl', category: 'DOWNLOADER', tags: ['vimeo', 'download'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'url', type: 'query', required: true, description: 'Vimeo URL' }], example: { request: 'GET /api/tools/vimeo-dl?url=...', response: '{"status":true,"data":{"downloadUrl":"https://..."}}' } },


  { name: 'Blur Image', description: 'Generate blurred placeholder image', method: 'GET', endpoint: '/api/tools/blur-img', category: 'IMAGE', tags: ['blur', 'image'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'width', type: 'query', required: false, description: 'Width' }, { name: 'height', type: 'query', required: false, description: 'Height' }], example: { request: 'GET /api/tools/blur-img?width=640&height=480', response: '{"status":true,"data":{"url":"https://..."}}' } },
  { name: 'Color Convert', description: 'Convert colors between HEX/RGB/HSL', method: 'GET', endpoint: '/api/tools/color-convert', category: 'IMAGE', tags: ['color', 'convert'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'color', type: 'query', required: true, description: 'Color value' }, { name: 'toFormat', type: 'query', required: false, description: 'Target format' }], example: { request: 'GET /api/tools/color-convert?color=%23FF5733&toFormat=rgb', response: '{"status":true,"data":{"rgb":"rgb(255,87,51)"}}' } },
  { name: 'Color Palette', description: 'Generate color palette from hex', method: 'GET', endpoint: '/api/tools/color-palette', category: 'IMAGE', tags: ['color', 'palette'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'hex', type: 'query', required: true, description: 'Hex color' }], example: { request: 'GET /api/tools/color-palette?hex=FF5733', response: '{"status":true,"data":{"palette":[...]}}' } },
  { name: 'Gradient', description: 'Generate gradient image', method: 'GET', endpoint: '/api/tools/gradient', category: 'IMAGE', tags: ['gradient', 'color'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'to', type: 'query', required: true, description: 'End color' }, { name: 'direction', type: 'query', required: false, description: 'Direction' }], example: { request: 'GET /api/tools/gradient?to=ff0000', response: '{"status":true,"data":{"url":"https://..."}}' } },
  { name: 'Wallpaper', description: 'Get random wallpapers', method: 'GET', endpoint: '/api/tools/wallpaper', category: 'IMAGE', tags: ['wallpaper', 'background'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'categories', type: 'query', required: false, description: 'Categories' }, { name: 'purity', type: 'query', required: false, description: 'Purity filter' }], example: { request: 'GET /api/tools/wallpaper', response: '{"status":true,"data":{"url":"https://..."}}' } },

  { name: 'COVID Country', description: 'Get COVID stats by country', method: 'GET', endpoint: '/api/tools/covid-country', category: 'INFO', tags: ['covid', 'health'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }], example: { request: 'GET /api/tools/covid-country', response: '{"status":true,"data":{"countries":[...]}}' } },
  { name: 'Earthquake', description: 'Get recent earthquake data', method: 'GET', endpoint: '/api/tools/earthquake', category: 'INFO', tags: ['earthquake', 'disaster'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'limit', type: 'query', required: false, description: 'Max results' }], example: { request: 'GET /api/tools/earthquake?limit=10', response: '{"status":true,"data":{"earthquakes":[...]}}' } },
  { name: 'Flight Tracker', description: 'Track flights between airports', method: 'GET', endpoint: '/api/tools/flight', category: 'INFO', tags: ['flight', 'travel'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'from', type: 'query', required: true, description: 'Origin airport' }, { name: 'to', type: 'query', required: true, description: 'Destination airport' }, { name: 'date', type: 'query', required: true, description: 'Date' }], example: { request: 'GET /api/tools/flight?from=CGK&to=SIN&date=2024-01-15', response: '{"status":true,"data":{"flights":[...]}}' } },
  { name: 'Forex', description: 'Get forex exchange rates', method: 'GET', endpoint: '/api/tools/forex', category: 'INFO', tags: ['forex', 'currency'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'from', type: 'query', required: true, description: 'Source currency' }, { name: 'to', type: 'query', required: true, description: 'Target currency' }], example: { request: 'GET /api/tools/forex?from=USD&to=IDR', response: '{"status":true,"data":{"rate":15000}}' } },
  { name: 'GDP Data', description: 'Get GDP data by country', method: 'GET', endpoint: '/api/tools/gdp', category: 'INFO', tags: ['gdp', 'economy'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'country', type: 'query', required: true, description: 'Country name' }], example: { request: 'GET /api/tools/gdp?country=indonesia', response: '{"status":true,"data":{"gdp":1186000000000}}' } },
  { name: 'GeoIP', description: 'Get IP geolocation', method: 'GET', endpoint: '/api/tools/geoip', category: 'INFO', tags: ['geoip', 'location'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'ip', type: 'query', required: false, description: 'IP address' }], example: { request: 'GET /api/tools/geoip?ip=8.8.8.8', response: '{"status":true,"data":{"country":"US","city":"Mountain View"}}' } },
  { name: 'HDI Index', description: 'Get Human Development Index data', method: 'GET', endpoint: '/api/tools/hdi-index', category: 'INFO', tags: ['hdi', 'development'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }], example: { request: 'GET /api/tools/hdi-index', response: '{"status":true,"data":[...]}}' } },
  { name: 'IP Whois', description: 'Whois lookup for IP address', method: 'GET', endpoint: '/api/tools/ip-whois', category: 'INFO', tags: ['ip', 'whois'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'ip', type: 'query', required: true, description: 'IP address' }], example: { request: 'GET /api/tools/ip-whois?ip=8.8.8.8', response: '{"status":true,"data":{...}}' } },
  { name: 'Population', description: 'Get population data by country', method: 'GET', endpoint: '/api/tools/population', category: 'INFO', tags: ['population', 'demographics'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'country', type: 'query', required: false, description: 'Country name' }], example: { request: 'GET /api/tools/population?country=indonesia', response: '{"status":true,"data":{"population":273523615}}' } },
  { name: 'REST Country', description: 'Get country data from REST API', method: 'GET', endpoint: '/api/tools/rest-country', category: 'INFO', tags: ['country', 'rest'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'code', type: 'query', required: true, description: 'Country code' }], example: { request: 'GET /api/tools/rest-country?code=ID', response: '{"status":true,"data":{...}}' } },
  { name: 'Sentiment', description: 'Analyze text sentiment', method: 'GET', endpoint: '/api/tools/sentiment', category: 'INFO', tags: ['sentiment', 'nlp'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'text', type: 'query', required: true, description: 'Text to analyze' }], example: { request: 'GET /api/tools/sentiment?text=I+love+this', response: '{"status":true,"data":{"sentiment":"positive","score":0.8}}' } },
  { name: 'Space News', description: 'Get latest space news', method: 'GET', endpoint: '/api/tools/space-news', category: 'INFO', tags: ['space', 'news'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'limit', type: 'query', required: false, description: 'Max items' }], example: { request: 'GET /api/tools/space-news?limit=5', response: '{"status":true,"data":{"articles":[...]}}' } },
  { name: 'Stock Price', description: 'Get stock price data', method: 'GET', endpoint: '/api/tools/stock', category: 'INFO', tags: ['stock', 'finance'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'symbol', type: 'query', required: true, description: 'Stock symbol' }], example: { request: 'GET /api/tools/stock?symbol=AAPL', response: '{"status":true,"data":{"price":150.25}}' } },
  { name: 'Train Schedule', description: 'Get train schedules', method: 'GET', endpoint: '/api/tools/train', category: 'INFO', tags: ['train', 'travel'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'from', type: 'query', required: true, description: 'Origin' }, { name: 'to', type: 'query', required: true, description: 'Destination' }], example: { request: 'GET /api/tools/train?from=Jakarta&to=Bandung', response: '{"status":true,"data":{"trains":[...]}}' } },
  { name: 'Timezone Convert', description: 'Convert between timezones', method: 'GET', endpoint: '/api/tools/tz-convert', category: 'INFO', tags: ['timezone', 'convert'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'to', type: 'query', required: true, description: 'Target timezone' }, { name: 'from', type: 'query', required: false, description: 'Source timezone' }], example: { request: 'GET /api/tools/tz-convert?to=America/New_York', response: '{"status":true,"data":{"time":"..."}}' } },
  { name: 'UN Country', description: 'Get UN country data', method: 'GET', endpoint: '/api/tools/un-country', category: 'INFO', tags: ['un', 'country'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'country', type: 'query', required: true, description: 'Country name' }], example: { request: 'GET /api/tools/un-country?country=indonesia', response: '{"status":true,"data":{...}}' } },
  { name: 'Weather Forecast', description: 'Get weather forecast', method: 'GET', endpoint: '/api/tools/weather-forecast', category: 'INFO', tags: ['weather', 'forecast'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'city', type: 'query', required: true, description: 'City name' }], example: { request: 'GET /api/tools/weather-forecast?city=Jakarta', response: '{"status":true,"data":{"forecast":[...]}}' } },

  { name: 'Album Art', description: 'Search album artwork', method: 'GET', endpoint: '/api/tools/album-art', category: 'MEDIA', tags: ['album', 'art', 'music'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'q', type: 'query', required: true, description: 'Album name' }], example: { request: 'GET /api/tools/album-art?q=Thriller', response: '{"status":true,"data":{"results":[...]}}' } },
  { name: 'Artist Info', description: 'Get music artist info', method: 'GET', endpoint: '/api/tools/artist-info', category: 'MEDIA', tags: ['artist', 'music'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'q', type: 'query', required: true, description: 'Artist name' }], example: { request: 'GET /api/tools/artist-info?q=Eminem', response: '{"status":true,"data":{"name":"Eminem",...}}' } },
  { name: 'Movie Detail', description: 'Get detailed movie info', method: 'GET', endpoint: '/api/tools/movie-detail', category: 'MEDIA', tags: ['movie', 'detail'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'id', type: 'query', required: true, description: 'IMDB ID' }], example: { request: 'GET /api/tools/movie-detail?id=tt1375666', response: '{"status":true,"data":{...}}' } },
  { name: 'Music Search', description: 'Search music tracks', method: 'GET', endpoint: '/api/tools/music-search', category: 'MEDIA', tags: ['music', 'search'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'q', type: 'query', required: true, description: 'Search query' }], example: { request: 'GET /api/tools/music-search?q=shape+of+you', response: '{"status":true,"data":{"results":[...]}}' } },
  { name: 'Podcast', description: 'Search podcasts', method: 'GET', endpoint: '/api/tools/podcast', category: 'MEDIA', tags: ['podcast', 'audio'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'q', type: 'query', required: true, description: 'Search query' }], example: { request: 'GET /api/tools/podcast?q=technology', response: '{"status":true,"data":{"results":[...]}}' } },
  { name: 'Sound Effects', description: 'Search sound effects', method: 'GET', endpoint: '/api/tools/sound-fx', category: 'MEDIA', tags: ['sound', 'sfx'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'q', type: 'query', required: true, description: 'Search query' }], example: { request: 'GET /api/tools/sound-fx?q=explosion', response: '{"status":true,"data":{"results":[...]}}' } },
  { name: 'TV Show', description: 'Search TV shows', method: 'GET', endpoint: '/api/tools/tv-show', category: 'MEDIA', tags: ['tv', 'show'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'q', type: 'query', required: true, description: 'Search query' }], example: { request: 'GET /api/tools/tv-show?q=breaking+bad', response: '{"status":true,"data":{"results":[...]}}' } },

  { name: 'QR Decode', description: 'Decode QR code', method: 'GET', endpoint: '/api/tools/qr-decode', category: 'TOOLS', tags: ['qr', 'decode'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'text', type: 'query', required: true, description: 'QR image URL' }], example: { request: 'GET /api/tools/qr-decode?text=https://...', response: '{"status":true,"data":{"decoded":"..."}}' } },
  { name: 'Reddit Search', description: 'Search Reddit posts', method: 'GET', endpoint: '/api/tools/reddit-search', category: 'TOOLS', tags: ['reddit', 'search'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'q', type: 'query', required: true, description: 'Search query' }, { name: 'subreddit', type: 'query', required: false, description: 'Subreddit' }], example: { request: 'GET /api/tools/reddit-search?q=javascript', response: '{"status":true,"data":{"posts":[...]}}' } },
  { name: 'Text to Speech', description: 'Convert text to speech', method: 'GET', endpoint: '/api/tools/tts', category: 'TOOLS', tags: ['tts', 'speech'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'text', type: 'query', required: true, description: 'Text' }, { name: 'lang', type: 'query', required: false, description: 'Language' }], example: { request: 'GET /api/tools/tts?text=Hello', response: '{"status":true,"data":{"url":"https://..."}}' } },
  { name: 'UUID Validate', description: 'Validate UUID format', method: 'GET', endpoint: '/api/tools/uuid-validate', category: 'TOOLS', tags: ['uuid', 'validate'], cost: 1, params: [{ name: 'x-api-key', type: 'header', required: true, description: 'Your API key' }, { name: 'uuid', type: 'query', required: true, description: 'UUID' }], example: { request: 'GET /api/tools/uuid-validate?uuid=550e8400-e29b-41d4-a716-446655440000', response: '{"status":true,"data":{"valid":true}}' } },
]

export const categoryColors: Record<string, string> = {
  SEND: 'text-blue-400',
  TEXT: 'text-green-400',
  IMAGE: 'text-pink-400',
  DOWNLOADER: 'text-red-400',
  ANIME: 'text-purple-400',
  MEDIA: 'text-yellow-400',
  INFO: 'text-cyan-400',
  DATA: 'text-orange-400',
  TOOLS: 'text-slate-300',
  GAMES: 'text-emerald-400'
}
